language: julia
os:
  - linux
  - osx
julia:
  - 0.7
  - 1.0
  - nightly
matrix:
  allow_failures:
    - julia: nightly
notifications:
  email: false
before_script:
  - export PATH=$HOME/.local/bin:$PATH
after_success:
  - julia -e 'import Pkg; Pkg.add("Documenter"); include(joinpath("docs", "make.jl"))'
  - julia -e 'import Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
